set -g default-terminal "screen-256color"
set -g pane-border-status top
set -g pane-border-format " #[bold]#{pane_title}#[default] "
set -g status-style "bg=colour236,fg=colour250"
set -g window-status-current-style "bg=colour33,fg=colour231,bold"
set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
